CREATE TABLE TB_PRODUCTOS_EXAMEN(
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR2 (20) NOT NULL,
    TIPO VARCHAR2 (15) CHECK (TIPO IN ('ALIMENTACIÓN','ELECTRÓNICA','ROPA')) NOT NULL,
    PRECIO DECIMAL NOT NULL,
    STOCK INT NOT NULL
);