-- CONSULTAS CON CONDICIONES
SELECT * FROM TB_GUERRERO
WHERE FK_VEHICULO_GUERRA = 1
ORDER BY ID DESC, NOMBRE ASC
LIMIT 3;

SELECT * FROM TB_GUERRERO WHERE ID BETWEEN 1 AND 11;
SELECT * FROM TB_GUERRERO;

SELECT * FROM TB_GUERRERO
WHERE FK_VEHICULO_GUERRA=1
ORDER BY RESISTENCIA DESC, FUERZA DESC, NOMBRE DESC
LIMIT 5;

SELECT SUM(g.FUERZA) as SUMA_FUERZA, 
AVG(RESISTENCIA) as MEDIA_RESISTENCIA, 
FK_VEHICULO_GUERRA
FROM TB_GUERRERO
WHERE ID BETWEEN 1 AND 11
GROUP BY FK_VEHICULO_GUERRA;

select * from TB_GUERRERO WHERE NOMBRE IN ('GUERRERO1','GUERRERO2')

-- UPDATES
UPDATE TB_GUERRERO
SET FUERZA=0, RESISTENCIA=10
WHERE NOMBRE='GUERRERO6';

UPDATE TB_GUERRERO
SET FUERZA=1, RESISTENCIA=7
WHERE NOMBRE IN ('GUERRERO10','GUERRERO9');


-- DELETES
SELECT ID FROM TB_GUERRERO ORDER BY ID DESC LIMIT 1;

DELETE FROM TB_GUERRERO WHERE ID = (SELECT ID FROM TB_GUERRERO ORDER BY ID DESC LIMIT 1);

DELETE FROM TB_GUERRERO WHERE ID = 19;
